services:
    admin.form.language_choice:
        class: AdminBundle\Form\Type\Generic\LanguageChoiceFormService
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']

    admin.form.category_choice:
        class: AdminBundle\Form\Type\Generic\CategoryChoiceFormService
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']

    admin.form.word:
        class: AdminBundle\Form\Type\WordType
        arguments: ['@admin.form.language_choice', '@admin.form.category_choice']
        tags:
            - { name: form.type }

    admin.form.course:
        class: AdminBundle\Form\Type\CourseType
        arguments: ['@admin.form.language_choice']
        tags:
            - { name: form.type }

    admin.form.language_info:
        class: AdminBundle\Form\Type\LanguageInfoType
        arguments: ['@admin.form.language_choice']
        tags:
            - { name: form.type }

    admin.form.language_info_text_type:
        class: AdminBundle\Form\Type\Generic\NameTextCollectionType
        arguments: ['AdminBundle\Entity\LanguageInfoText']
        tags:
            - { name: form.type }

    admin.form.lesson_text_type:
        class: AdminBundle\Form\Type\Generic\NameTextCollectionType
        arguments: ['AdminBundle\Entity\LessonText']
        tags:
            - { name: form.type }

    admin.validation_group_resolver:
        class: AdminBundle\ValidationGroupResolver\GroupResolver
        arguments: ['@request_stack']