services:
    admin.custom_file_uploader_listener:
        class: AdminBundle\Listener\Custom\FileUploaderListener
        arguments: ['@admin.file_uploader', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: admin.upload_file_event, method: onFileUpload }

    admin.custom_pre_persist_listener:
        class: AdminBundle\Listener\Custom\PrePersistListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: admin.pre_persist_event, method: onPrePersist }

    admin.custom_post_persist_listener:
        class: AdminBundle\Listener\Custom\PostPersistListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: admin.post_persist_event, method: onPostPersist }

    admin.custom_pre_update_listener:
        class: AdminBundle\Listener\Custom\PreUpdateListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: admin.pre_update_event, method: onPreUpdate }