version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: langland_monolith
    ports:
      - 8080:80
    links:
      - mysql
    volumes:
      - .:/monolith/app
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: langland
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
