services:
    admin.validator.unique_constraint_validator:
        class: AdminBundle\Validator\Constraint\UniqueConstraintValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator }

    word.form:
        class: AdminBundle\Form\Type\WordType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    admin.pre_persist:
        class: AdminBundle\Listener\EntityEventSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    admin.file_namer:
        class: Library\App\FileNamer
        arguments: ['@doctrine.orm.entity_manager']

    admin.image_resizer:
        class: Library\App\ImageResize

    admin.file_uploader:
        class: AdminBundle\Helper\FileUploader
        arguments: ['%image_upload_dir%', '@admin.image_resizer', '@admin.file_namer']