services:
    admin.validator.unique_constraint_validator:
        class: AdminBundle\Validator\Constraint\UniqueConstraintValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator }

    library_entity_factory:
        class: Library\EntityFactory

    admin.custom_file_uploader_listener:
        class: AdminBundle\Listener\Custom\FileUploaderListener
        arguments: ['@admin.file_uploader', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: admin.upload_file_event, method: onFileUpload }

    admin.custom_pre_persist_listener:
        class: AdminBundle\Listener\Custom\PrePersistListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: admin.pre_persist_event, method: onPrePersist }

    admin.custom_post_persist_listener:
        class: AdminBundle\Listener\Custom\PostPersistListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: admin.post_persist_event, method: onPostPersist }

    admin.custom_pre_update_listener:
        class: AdminBundle\Listener\Custom\PreUpdateListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: admin.pre_update_event, method: onPreUpdate }

    admin.form.word:
        class: AdminBundle\Form\Type\WordType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    admin.form.question_game:
        class: AdminBundle\Form\Type\QuestionGameType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    admin.form.course:
        class: AdminBundle\Form\Type\CourseType
        arguments: ['@doctrine.orm.entity_manager', '@admin.validation_group_resolver']
        tags:
            - { name: form.type }

    admin.form.language_info:
        class: AdminBundle\Form\Type\LanguageInfoType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    admin.form.language_info_text_type:
        class: AdminBundle\Form\Type\Generic\NameTextCollectionType
        arguments: ['AdminBundle\Entity\LanguageInfoText']
        tags:
            - { name: form.type }

    admin.form.lesson_text_type:
        class: AdminBundle\Form\Type\Generic\NameTextCollectionType
        arguments: ['AdminBundle\Entity\LessonText']
        tags:
            - { name: form.type }

#    admin.validator.language_info_validator:
#        class: AdminBundle\Validator\Constraint\OneLanguageInfoConstraintValidator
#        arguments: ['@doctrine.orm.entity_manager']
#        tags:
#            - { name: validator.constraint_validator }

    admin.form.lesson_working_data:
        class: AdminBundle\Form\Type\LessonWorkingDataType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    admin.validation_group_resolver:
        class: AdminBundle\ValidationGroupResolver\GroupResolver
        arguments: ['@request_stack']

    admin.file_namer:
        class: Library\FileNamer
        arguments: ['@doctrine.orm.entity_manager']

    admin.image_resizer:
        class: Library\ImageResize

    admin.file_uploader:
        class: Library\FileUploader
        arguments: ['%upload_dirs%', '@admin.image_resizer', '@admin.file_namer']

    lib.manual_validator:
        class: Library\ManualValidator
        arguments: ['@validator']

    admin.game_entity_creator:
        class: AdminBundle\Helper\GameEntityCreator
        arguments: ['@doctrine.orm.entity_manager']