services:
    admin.validator.language_exists_validator:
        class: AdminBundle\Validator\Constraint\LanguageExistsConstraintValidator
        arguments: ['@api.shared.language_repository']
        tags:
            - { name: validator.constraint_validator }