<?php

namespace AppBundle\Repository;

/**
 * LearningUserLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LearningUserLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
