<?php

namespace AppBundle\Repository;

/**
 * LearningUserGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LearningUserGameRepository extends \Doctrine\ORM\EntityRepository
{
}
