<?php

namespace AppBundle\Repository;

/**
 * LearningUserCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LearningUserCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
