imports:
    - { resource: ../prod/config.yml }

twig:
    cache: false

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels:
        - generic_exception
    handlers:
        generic_exception:
            type: stream
            path: '%kernel.logs_dir%/exception.log'
            level: alert
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        security:
            level: error
            type: stream
            path: '%kernel.logs_dir%/security.log'
            channels: [security]
        console:
            type: console
            channels: ['!event', '!doctrine']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']
