imports:
    - { resource: test_parameters.yml }
    - { resource: test_security.yml }
    - { resource: services.yml }
    - { resource: "@ArmorBundle/Resources/config/services.xml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@AppBundle/Resources/config/services.yml" }

    - { resource: vendor_config/jms_serializer.yml }
    - { resource: vendor_config/sylius_resources.yml }

parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    test: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        storage_id: session.storage.mock_file
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: false
    profiler:
        collect: false

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
