app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

public:
    resource: "@PublicBundle/Resources/config/routing/routing.yml"
    prefix:   /

armor:
    resource: "@ArmorBundle/Resources/config/routing/routing.xml"
    prefix:   /

admin:
    resource: '@AdminBundle/Resources/config/routing/routing.yml'

api_blue_dot_loader:
    resource: .
    type: blue_dot_base_route
