<?php

namespace AdminBundle\Repository;

/**
 * GameDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameDataRepository extends \Doctrine\ORM\EntityRepository
{
}
