<?php

namespace AdminBundle\Repository;

/**
 * WorkingDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkingDataRepository extends \Doctrine\ORM\EntityRepository
{
}
