admin_category_index:
    path: /category
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.category_controller:indexAction}

admin_category_create:
    path: /category/create
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.category_controller:createAction }

admin_category_new:
    path: /category/new
    methods: [POST]
    defaults: { _controller: langland.learning_metadata.controller.category_controller:newAction }

admin_category_update:
    path: /category/update/{id}
    methods: [POST, GET]
    defaults: { _controller: langland.learning_metadata.controller.category_controller:updateAction }