admin_course_index:
    path: /course
    methods: [GET]
    defaults:
        _controller: admin.controller.course:indexAction
        _sylius:
            template: Admin/Template/Panel/_listing.html.twig

admin_course_create:
    path: /course/create
    methods: [POST, GET]
    defaults:
        _controller: admin.controller.course:createAction
        _sylius:
            template: Admin/Template/Panel/_action.html.twig
            redirect: admin_course_create

admin_course_update:
    path: /course/update/{id}
    methods: [POST, GET]
    defaults:
        _controller: admin.controller.course:updateAction
        _sylius:
            template: Admin/Template/Panel/_action.html.twig
            redirect: admin_course_update

admin_course_managment:
  path: /course/manage/{courseId}
  methods: [GET]
  defaults:
      _controller: admin.controller.course:manageAction