course_create:
    path: /create
    defaults: { _controller: AdminBundle:Course:create }
    methods: [POST, GET]

course_index:
    path: /
    defaults: { _controller: AdminBundle:Course:index }
    methods: [GET]

course_edit:
    path: /edit/{id}
    defaults: { _controller: AdminBundle:Course:edit }
    methods: [GET, POST]

course_manage:
    path: /manage/{id}
    defaults: { _controller: AdminBundle:Course:manage }
    methods: [GET]