admin_course_create:
    path: /create
    defaults: { _controller: AdminBundle:Course:create }
    methods: [POST, GET]

admin_course_index:
    path: /
    defaults: { _controller: AdminBundle:Course:index }
    methods: [GET]

admin_course_edit:
    path: /edit/{id}
    defaults: { _controller: AdminBundle:Course:edit }
    methods: [GET, POST]

course_manager:
  resource: "@AdminBundle/Resources/config/routing/api/course/course.yml"
  prefix: /manage
  host: '%host%'