admin_course_index:
    path: /course
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.course_controller:indexAction }

admin_course_create:
    path: /course/create
    methods: [POST, GET]
    defaults: { _controller: langland.learning_metadata.controller.course_controller:createAction }

admin_course_new:
    path: /course/new
    methods: [POST]
    defaults: { _controller: langland.learning_metadata.controller.course_controller:newAction }

admin_course_update:
    path: /course/update/{id}
    methods: [POST, GET]
    defaults: { _controller: langland.learning_metadata.controller.course_controller:updateAction }

admin_course_managment:
    path: /course/manage/{courseId}
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.course_controller:manageAction }

admin_course:
  resource: "@AdminBundle/Resources/config/routing/api/course_managment/main.yml"
  prefix: /course/manage/{courseId}
  host: '%host%'