admin_language_index:
    path: /
    defaults: { _controller: AdminBundle:Language:index }
    methods: [GET]

admin_language_create:
    path: /create
    defaults: { _controller: AdminBundle:Language:create }
    methods: [POST, GET]

admin_language_edit:
    path: /edit/{id}
    defaults: { _controller: AdminBundle:Language:edit }
    methods: [POST, GET]