admin_language_index:
    path: /langauge
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.language_controller:indexAction }

admin_language_create:
    path: /language/create
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.language_controller:createAction }

admin_language_new:
    path: /language/new
    methods: [POST]
    defaults: { _controller: langland.learning_metadata.controller.language_controller:newAction }

admin_language_update:
    path: /language/update/{id}
    methods: [POST, GET]
    defaults: { _controller: langland.learning_metadata.controller.language_controller:updateAction }