admin_language_index:
    path: /langauge
    methods: [GET]
    defaults: { _controller: learning_metadata.controller.language:indexAction }

admin_language_create:
    path: /language/create
    methods: [GET]
    defaults: { _controller: learning_metadata.controller.language:createAction }

admin_language_new:
    path: /language/new
    methods: [POST]
    defaults: { _controller: learning_metadata.controller.language:newAction }

admin_language_update:
    path: /language/update/{id}
    methods: [POST, GET]
    defaults: { _controller: learning_metadata.controller.language:updateAction }