admin_lesson_index:
    path: /lessons
    methods: [GET]
    defaults: { _controller: learning_metadata.controller.lesson:indexViewAction }

admin_lesson_create:
    path: /lesson/create
    methods: [GET]
    defaults: { _controller: learning_metadata.controller.lesson:createViewAction }

admin_lesson_update_view:
    path: /lesson/edit/{lessonId}
    methods: [GET]
    defaults: { _controller: learning_metadata.controller.lesson:editViewAction }

admin_api_lesson_new:
    path: /api/v1/lesson/new
    methods: [POST]
    defaults: { _controller: learning_metadata.controller.lesson:newAction }
    requirements:
        _format: json

admin_api_lesson_update:
    path: /api/v1/lesson/update
    methods: [PUT]
    defaults: { _controller: learning_metadata.controller.lesson:updateAction }
    requirements:
        _format: json

admin_get_lesson_by_id:
    path: /api/v1/lesson/{lessonId}
    defaults: { _controller: learning_metadata.controller.lesson:getLessonById }
    methods: [GET]
    requirements:
        _format: json