lesson_manage:
    path: /manage/{lessonId}
    defaults: { _controller: AdminBundle:Lesson:manage }
    methods: [GET, POST]
    requirements:
        lessonId: \d+

lesson_working_data_create:
    path: /manage/{lessonId}/create
    defaults: { _controller: AdminBundle:LessonWorkingData:create }

lesson_working_data_edit:
    path: /manage/{lessonId}/edit
    defaults: { _controller: AdminBundle:LessonWorkingData:edit }