create_lesson:
    path: /create
    defaults: { _controller: AdminBundle:Lesson:create }
    methods: [POST]

get_lessons_by_class:
    path: /find-lessons-by-class
    defaults: { _controller: AdminBundle:Lesson:findLessonsByClass }
    methods: [POST]

rename_lesson:
    path: /rename-lesson
    defaults: { _controller: AdminBundle:Lesson:renameLesson }
    methods: [POST]