admin_dashboard:
  path: /dashboard
  defaults: { _controller: learning_metadata.controller.dashboard:dashboardAction }
  methods: [GET]

admin_language:
  resource: "@AdminBundle/Resources/config/routing/api/language.yml"
  prefix: /
  host: '%host%'

admin_category:
  resource: "@AdminBundle/Resources/config/routing/api/category.yml"
  prefix: /
  host: '%host%'

admin_language_info:
  resource: "@AdminBundle/Resources/config/routing/api/language_info.yml"
  prefix: /
  host: '%host%'

admin_word:
  resource: "@AdminBundle/Resources/config/routing/api/word.yml"
  prefix: /
  host: '%host%'

admin_sound:
  resource: "@AdminBundle/Resources/config/routing/api/sound.yml"
  prefix: /
  host: '%host%'

admin_lesson:
  resource: "@AdminBundle/Resources/config/routing/api/lesson.yml"
  prefix: /
  host: '%host%'