add_sentence:
    path: /create
    defaults: { _controller: AdminBundle:Sentence:create }
    methods: [POST]

find_lesson_sentence:
    path: /find-lesson-sentence
    defaults: { _controller: AdminBundle:Sentence:findLessonSentence }
    methods: [POST]

update_lesson_sentence:
    path: /update-lesson-sentence
    defaults: { _controller: AdminBundle:Sentence:updateLessonSentence }

find_internal_names:
    path: /find-internal-names
    defaults: { _controller: AdminBundle:Sentence:findInternalNames }
    methods: [POST]