#admin_sound_index:
#    path: /sounds
#    methods: [GET]
#    defaults:
#        _controller: admin.controller.sound:indexAction
#        _sylius:
#            template: Admin/Template/Panel/_listing.html.twig
#
#admin_sound_create:
#    path: /sound/create
#    methods: [POST, GET]
#    defaults:
#        _controller: admin.controller.sound:createAction
#        _sylius:
#            template: Admin/Template/Panel/_action.html.twig
#            redirect: admin_sound_create
#
#admin_sound_update:
#    path: /sound/update/{id}
#    methods: [POST, GET]
#    defaults:
#        _controller: admin.controller.sound:updateAction
#        _sylius:
#            template: Admin/Template/Panel/_action.html.twig
#            redirect: admin_sound_update