sound_create:
    path: /create
    defaults: { _controller: AdminBundle:Sound:create }
    methods: [POST, GET]

sound_index:
    path: /
    defaults: { _controller: AdminBundle:Sound:index }
    methods: [GET]

admin_get_sounds:
    path: /
    defaults: { _controller: AdminBundle:Sound:findAllSounds }