admin_sound_create:
    path: /create
    defaults: { _controller: AdminBundle:Sound:create }
    methods: [POST, GET]

admin_sound_index:
    path: /
    defaults: { _controller: AdminBundle:Sound:index }
    methods: [GET]

admin_find_sounds:
    path: /find-sounds
    defaults: { _controller: AdminBundle:Ajax/Sound:findSounds }
    methods: [GET]