create_theory:
    path: /create
    defaults: { _controller: AdminBundle:Theory:create }
    methods: [POST]

rename_theory:
    path: /rename
    defaults: { _controller: AdminBundle:Theory:rename }
    methods: [POST]

create_theory_deck:
    path: /create-deck
    defaults: { _controller: AdminBundle:Theory:createTheoryDeck }
    methods: [POST]

find_all_by_lesson:
    path: /find-all-by-lesson
    defaults: { _controller: AdminBundle:Theory:findAllByLesson }
    methods: [POST]

find_decks_by_theory:
    path: /find-decks-by-theory
    defaults: { _controller: AdminBundle:Theory:findAllDecksByTheory }
    methods: [POST]

find_deck_by_internal_name:
    path: /find-deck-by-internal-name
    defaults: { _controller: AdminBundle:Theory:findDeckByInternalName }

find_deck_by_id:
    path: /find-deck
    defaults: { _controller: AdminBundle:Theory:findDeck }
    methods: [POST]

find_deck_sounds:
    path: /find-deck-sounds
    defaults: { _controller: AdminBundle:Theory:findDeckSounds }
    methods: [POST]
