admin_word_create:
    path: /create
    defaults: { _controller: AdminBundle:Word:create }
    methods: [GET, POST]

admin_word_edit:
    path: /edit/{id}
    defaults: { _controller: AdminBundle:Word:edit }
    methods: [GET, POST]

admin_word_index:
    path: /
    defaults: { _controller: AdminBundle:Word:index }
    methods: [GET]

admin_word_remove:
    path: /remove/{id}
    defaults: { _controller: AdminBundle:Word:remove }
    methods: [GET]

word_autocomplete_search:
    path: /search/{search}
    defaults: { _controller: AdminBundle:Ajax/Word:autocompleteSearch }
    methods: [POST]

find_words_by_ids:
    path: /search/id/{ids}
    defaults: { _controller: AdminBundle:Ajax/Word:findTagWordsByIds }
    methods: [POST]