admin_word_index:
    path: /words
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.word:indexAction }

admin_word_create:
    path: /word/create
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.word:createAction }

admin_word_new:
    path: /word/new
    methods: [POST]
    defaults: { _controller: langland.learning_metadata.controller.word:newAction }

admin_word_update:
    path: /word/update/{id}
    methods: [POST, GET]
    defaults: { _controller: langland.learning_metadata.controller.word:updateAction }

#admin_word_remove:
#    path: /remove/{id}
#    defaults: { _controller: AdminBundle:Word:remove }
#    methods: [GET]
#
#word_autocomplete_search:
#    path: /search/{search}
#    defaults: { _controller: AdminBundle:Ajax/Word:autocompleteSearch }
#    methods: [POST]
#
#find_words_by_ids:
#    path: /search/id/{ids}
#    defaults: { _controller: AdminBundle:Ajax/Word:findTagWordsByIds }
#    methods: [POST]