word_create:
    path: /create
    defaults: { _controller: AdminBundle:Word:create }
    methods: [GET, POST]

word_edit:
    path: /edit/{id}
    defaults: { _controller: AdminBundle:Word:edit }
    methods: [GET, POST]

word_index:
    path: /
    defaults: { _controller: AdminBundle:Word:index }
    methods: [GET]