admin_word_index:
    path: /words
    methods: [GET]
    defaults:
        _controller: admin.controller.word:indexAction
        _sylius:
            template: Admin/Template/Panel/_listing.html.twig

admin_word_create:
    path: /word/create
    methods: [POST, GET]
    defaults:
        _controller: admin.controller.word:createAction
        _sylius:
            template: Admin/Template/Panel/_action.html.twig
            redirect: admin_word_create

admin_word_update:
    path: /word/update/{id}
    methods: [POST, GET]
    defaults:
        _controller: admin.controller.word:updateAction
        _sylius:
            template: Admin/Template/Panel/_action.html.twig
            redirect: admin_word_update

admin_word_remove:
    path: /remove/{id}
    defaults: { _controller: AdminBundle:Word:remove }
    methods: [GET]

word_autocomplete_search:
    path: /search/{search}
    defaults: { _controller: AdminBundle:Ajax/Word:autocompleteSearch }
    methods: [POST]

find_words_by_ids:
    path: /search/id/{ids}
    defaults: { _controller: AdminBundle:Ajax/Word:findTagWordsByIds }
    methods: [POST]