app_course_language_info_exists:
    path: /is-info-looked
    defaults: { _controller: AppBundle:Api/Course:isInfoLooked }
    methods: [GET]

app_course_language_infos:
    path: /find-language-info
    defaults: { _controller: AppBundle:Api/Course:findLanguageInfos }
    methods: [GET]

app_course_mark_info_looked:
    path: /mark-info-looked
    defaults: { _controller: AppBundle:Api/Course:markInfoLooked }
    methods: [POST]

app_language_course_list:
    path: /language-courses
    defaults: { _controller: AppBundle:Api/Course:findLanguageCourses }
    methods: [GET]