app_course_language_info_exists:
    path: /is-info-looked
    defaults: { _controller: AppBundle:Api/Course:isInfoLooked }

app_course_language_infos:
    path: /find-language-info
    defaults: { _controller: AppBundle:Api/Course:findLanguageInfos }

app_course_mark_info_looked:
    path: /mark-info-looked
    defaults: { _controller: AppBundle:Api/Course:markInfoLooked }

app_language_course_list:
    path: /find-language-course-list
    defaults: { _controller: AppBundle:Api/Course:findLanguageCourses }