app_lesson_list:
    path: /lesson-list/{learningUserCourseId}
    defaults: { _controller: AppBundle:Api/Lesson:lessonList }
    methods: [GET]

app_learning_user_mark_lesson_passed:
    path: /lesson/mark-lesson-passed
    defaults: { _controller: AppBundle:Api/Lesson:markLessonPassed }
    methods: [POST]

app_learning_user_lesson:
    path: /lesson/{learningUserLessonId}
    defaults: { _controller: AppBundle:Api/Lesson:findLearningUserLesson }
    methods: [GET]
    requirements:
        learningUserLessonId: \d+