app_lesson_list:
    path: /lesson-list/{learningUserCourseId}
    defaults: { _controller: AppBundle:Api/Lesson:lessonList }
    methods: [GET]

app_learning_user_mark_lesson_passed:
    path: /lesson/mark-lesson-passed
    defaults: { _controller: AppBundle:Api/Lesson:markLessonPassed }
    methods: [POST]

app_learning_user_lesson:
    path: /lesson/{learningUserLessonId}
    defaults: { _controller: AppBundle:Api/Lesson:findLearningUserLesson }
    methods: [GET]
    requirements:
        learningUserLessonId: \d+

app_find_available_games:
    path: /games/find-available-games/{learningUserCourseId}
    defaults: { _controller: AppBundle:Api/Games:findAvailableGames }
    methods: [GET]
    requirements:
        learningUserCourseId: \d+

app_decide_game_type:
    path: /game/decide-game-type/{learningUserGameId}
    defaults: { _controller: AppBundle:Api/Games/decideGameType }
    methods: [POST]
    requirements:
        learningUserGameId: \d+

app_initialize_selected_game:
    path: /game/{learningUserGameId}
    defaults: { _controller: AppBundle:Api/Games/initializeSelectedGame }
    methods: [POST]
    requirements:
        learningUserGameId: \d+
