app_logged_in_user:
    path: /logged-in
    defaults: { _controller: AppBundle:Api/User:findLoggedInUser }
    methods: [GET]

app_create_learning_user:
    path: /
    defaults: { _controller: AppBundle:Api/User:createLearningUser }
    methods: [POST]

app_find_learning_user:
    path: /
    defaults: { _controller: AppBundle:Api/User:findLearningUser }
    methods: [GET]