app_logged_in_user:
    path: /logged-in-user
    defaults: { _controller: AppBundle:Api/User:findLoggedInUser }
    methods: [GET]

app_learning_user_create:
    path: /create
    defaults: { _controller: AppBundle:Api/User:createLearningUser }
    methods: [POST]

app_learning_user_get:
    path: /
    defaults: { _controller: AppBundle:Api/User:getLearningUser }