app_course:
  resource: "@AppBundle/Resources/config/routing/api/course.yml"
  prefix: /courses
  host: '%host%'
  methods: [POST]

app_user:
  resource: "@AppBundle/Resources/config/routing/api/user.yml"
  prefix: /user
  host: '%host%'
  methods: [POST, GET]

app_language:
  resource: "@AppBundle/Resources/config/routing/api/language.yml"
  prefix: /languages
  host: '%host%'
  methods: [GET]

app_main_data:
  resource: "@AppBundle/Resources/config/routing/api/methodAppData.yml"
  prefix: /data
  host: '%host%'
  methods: [GET, POST]
