admin_dashboard:
    path:     /admin
    defaults: { _controller: AdminBundle:Main:dashboard }

language:
  resource: "@AdminBundle/Resources/config/routing/api/language.yml"
  prefix: /admin/language
  host: '%host%'

word:
  resource: "@AdminBundle/Resources/config/routing/api/word.yml"
  prefix: /admin/word
  host: '%host%'

category:
  resource: "@AdminBundle/Resources/config/routing/api/category.yml"
  prefix: /admin/category
  host: '%host%'

sound:
  resource: "@AdminBundle/Resources/config/routing/api/sound.yml"
  prefix: /admin/sound
  host: '%host%'

course:
  resource: "@AdminBundle/Resources/config/routing/api/course.yml"
  prefix: /admin/course

lesson_manage:
  resource: "@AdminBundle/Resources/config/routing/api/lesson_manage.yml"
  prefix: /admin/lesson