admin_dashboard:
  path: /admin/dashboard
  defaults: { _controller: AdminBundle:Main:dashboard}
  methods: [GET]

admin_main:
  resource: "@AdminBundle/Resources/config/routing/api/main.yml"
  prefix: /admin
  host: '%host%'