app_page_main_dashboard:
    path:     /
    defaults: { _controller: AppBundle:Dashboard:dashboard }
    methods: [GET]

app_page_course_dashboard:
    path: /course/{languageName}/{id}
    defaults: { _controller: AppBundle:Dashboard:coursePageDashboard }
    requirements:
        languageName: \w+
        id: \d+
    methods: [GET]

app_page_course_actual_app_dashboard:
    path: /dashboard/{courseName}/{learningUserCourseId}
    defaults: { _controller: AppBundle:Dashboard:methodAppDashboard }
    requirements:
        courseName: ^[A-Za-z0-9\-]+$
        courseHolderId: \d+
    methods: [GET]

app_page_lesson_list_dashboard:
    path: /dashboard/{courseName}/{learningUserCourseId}/lessons
    defaults: { _controller: AppBundle:Dashboard:lessonListDashboard }
    methods: [GET]
    requirements:
        courseHolderId: \d+