ArmorBundle\Entity\User:
    exclusion_policy: all
    properties:
        name:
            expose: true
            groups: [exposed_user]
        lastname:
            expose: true
            groups: [exposed_user]
        username:
            expose: true
            groups: [exposed_user]