ArmorBundle\Entity\LanguageSession:
    exclusion_policy: all
    properties:
        id:
            expose: true
            groups: [default, communication_model]

        createdAt:
            expose: true
            groups: [default, communication_model]
            type: DateTime<'Y-m-d H:m:s'>

        updatedAt:
            expose: true
            groups: [default, communication_model]
            type: DateTime<'Y-m-d H:m:s'>

        learningUser:
            type: PublicApiBundle\Entity\LearningUser
            expose: true
            groups: [default]