app_language_index:
    path: /
    defaults: { _controller: public_api.controller.language_index:languageIndexAction }
    methods: [GET]

app_actual_app:
    path: /language/{languageName}/{languageId}
    defaults: { _controller: public_api.controller.language_index:appAction }
    methods: [GET]

app_running_lesson:
    path: /lesson/{lessonName}/{learningLessonId}
    defaults: { _controller: public_api.controller.language_index:lessonRunnerAction }
    methods: [GET]

app_running_game:
    path: /game/{learningLessonId}
    defaults: { _controller: public_api.controller.language_index:lessonRunnerAction }
    methods: [GET]

