app_language_index:
    path: /
    defaults: { _controller: public_api.controller.language_index:languageIndexAction }
    methods: [GET]

app_actual_app:
    path: /{languageName}/{languageId}
    defaults: { _controller: public_api.controller.language_index:appAction }
    methods: [GET]

