AppBundle\Entity\LearningUserGame:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [games_list]
        hasPassed:
            expose: true
            groups: [games_list]
        questionGame:
            expose: true
            groups: [games_list]
            type: AdminBundle\Entity\Game\QuestionGame
            serialized_name: game
        wordGame:
            expose: true
            groups: [games_list]
            serialized_name: game
            type: AdminBundle\Entity\Game\WordGame