PublicApiBundle\Entity\PublicApiLanguage:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [default, communication_model]

        name:
            expose: true
            groups: [default, communication_model]

        listDescription:
            expose: true
            groups: [default, communication_model]
            serialized_name: description

        alreadyLearning:
            expose: true
            groups: [default, communication_model]
            serialized_name: description

        showOnPage:
            expose: true
            groups: [default, communication_model]

        images:
            expose: true
            groups: [default]

        createdAt:
            expose: true
            groups: [default, communication_model]
            type: DateTime<'Y-m-d H:m:s'>

        updatedAt:
            expose: true
            groups: [default, communication_model]
            type: DateTime<'Y-m-d H:m:s'>