admin_question_game_create:
    path: /create
    defaults: { _controller: AdminBundle:QuestionGame:create }
    methods: [GET, POST]

admin_question_game_edit:
    path: /edit/{gameId}
    defaults: { _controller: AdminBundle:QuestionGame:edit }
    methods: [GET, POST]