app_dashboard:
    path:     /langland
    defaults: { _controller: AppBundle:Dashboard:dashboard }
    methods: [GET]

app_course_dashboard:
    path: /langland/language-course/{languageName}/{id}
    defaults: { _controller: AppBundle:Course:dashboard }
    methods: [GET]

app_course_actual_app:
    path: /langland/language-course/{languageName}/{courseName}/{courseHolderId}
    defaults: { _controller: AppBundle:Api/Course:initApp }
    methods: [GET]

app_api:
  resource: "@AppBundle/Resources/config/routing/langland.yml"
  prefix: /langland/api
  host: '%host%'