app_dashboard:
    path:     /langland
    defaults: { _controller: AppBundle:Dashboard:dashboard }
    methods: [GET]

app_course_dashboard:
    path: /langland/course/{id}
    defaults: { _controller: AppBundle:Course:dashboard }

app_course:
  resource: "@AppBundle/Resources/config/routing/api/course/course.yml"
  prefix: /langland/courses
  host: '%host%'
  methods: [POST, GET]

app_user:
  resource: "@AppBundle/Resources/config/routing/api/user/user.yml"
  prefix: /langland/user
  host: '%host%'
  methods: [POST]

app_language:
  resource: "@AppBundle/Resources/config/routing/api/language/language.yml"
  prefix: /langland/language
  host: '%host%'
  methods: [POST]

