app_dashboard:
    path:     /langland
    defaults: { _controller: AppBundle:Dashboard:dashboard }
    methods: [GET]

app_course:
  resource: "@AppBundle/Resources/config/routing/api/course/course.yml"
  prefix: /langland/courses
  host: '%host%'
  methods: [POST, GET]

