AppBundle\Entity\LearningUserLesson:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [lesson_list]
            serialized_name: learningUserLessonId
        hasPassed:
            expose: true
            groups: [lesson_list]
            serialized_name: hasPassed
        isEligable:
            expose: true
            groups: [lesson_list]
            serialized_name: isEligable
        lesson:
            expose: true
            groups: ['lesson_list', 'lesson_text']
            type: AdminBundle\Entity\Lesson