AppBundle\Entity\LearningUserCourse:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [course_list]
        hasPassed:
            expose: true
            groups: [course_list]
            serialized_name: hasPassed
        language:
            expose: true
            groups: [course_list]
            type: AdminBundle\Entity\Language
        course:
            expose: true
            groups: [course_list]
            type: AdminBundle\Entity\Course