get_all_languages:
    path: /
    defaults: { _controller: public_api.controller.language:getAllShowableLanguages }
    methods: [GET]
    requirements:
        _format: json

get_language_info:
    path: /language-info/{languageId}
    defaults: { _controller: public_api.controller.language:getLanguageInfo }
    methods: [GET]
    requirements:
        _format: json
        languageId: \d+
