make_initial_data_creation:
    path: /make-initial-data-creation
    defaults: { _controller: public_api.controller.initial_data_creation_controller:makeInitialDataCreation }
    methods: [POST]
    requirements:
        _format: json

get_learning_lesson_presentation:
    path: /lesson-presentation
    defaults: { _controller: public_api.controller.learning_metadata:getLearningLessonPresentation }
    methods: [GET]
    requirements:
        _format: json

get_games_presentation:
    path: /games-presentation
    defaults: { _controller: public_api.controller.learning_metadata:getLearningGamesPresentation }
    methods: [GET]
    requirements:
        _format: json

get_learning_lesson_by_id:
    path: /get-learning-lesson-by-id/{id}
    defaults: { _controller: public_api.controller.learning_metadata:getLearningLessonById }
    methods: [GET]
    requirements:
        _format: json

get_runnable_game_by_learning_metadata:
    path: /get-running-game/{learningMetadataId}
    defaults: { _controller: public_api.controller.learning_metadata:getRunnableGameByLearningMetadataId }
    methods: [GET]