register_learning_user:
    path: /register-learning-user
    defaults: { _controller: langland.public_api.controller.learning_user:registerLearningUser }
    methods: [POST, PUT]

get_current_learning_user:
    path: /get-current-learning-user
    defaults: { _controller: langland.public_api.controller.learning_user:getCurrentLearningUser }
    methods: [GET]

get_dynamic_components_status:
    path: /get-dynamic-components-status
    defaults: { _controller: langland.public_api.controller.learning_user:getDynamicComponentsStatus }
    methods: [GET]

get_questions:
    path: /questions/get-questions
    defaults: { _controller: langland.public_api.controller.learning_user:getQuestions }
    methods: [GET]

mark_language_info_looked:
    path: /language-info/mark-language-info-looked
    defaults: { _controller: langland.public_api.controller.learning_user:markLanguageInfoLooked }
    methods: [POST]
    requirements:
        _format: json

mark_questions_answered:
    path: /questions/mark-questions-answered
    defaults: { _controller: langland.public_api.controller.learning_user:markQuestionsAnswered }
    methods: [POST]
    requirements:
        _format: json

validate_question_answers:
    path: /questions/validate
    defaults: { _controller: langland.public_api.controller.learning_user:validateQuestions }
    methods: [POST]
    requirements:
        _format: json

is_language_info_looked:
    path: /language-info/is-language-info-looked
    defaults: { _controller: langland.public_api.controller.learning_user:isLanguageInfoLooked }
    methods: [GET]
    requirements:
        _format: json