make_initial_data_creation:
    path: /make-initial-data-creation
    defaults: { _controller: public_api.controller.initial_data_creation_controller:makeInitialDataCreation }
    methods: [POST]
    requirements:
        _format: json