public_api_lesson:
  resource: "@PublicApiBundle/Resources/config/routing/api/lesson.yml"
  prefix: /lesson
  host: '%host%'
  methods: [GET]

public_api_language:
  resource: "@PublicApiBundle/Resources/config/routing/api/language.yml"
  prefix: /language
  host: '%host%'
  methods: [GET]

public_api_learning_user:
  resource: "@PublicApiBundle/Resources/config/routing/api/learning_user.yml"
  prefix: /learning-user
  host: '%host%'
  methods: [POST]