configuration:
    connection:
        host: 127.0.0.1
        database_name: langland
        user: root
        password: root

    sql_import: imports/public_api_language.yml

    simple:
        select:
            find_all_languages:
                sql: public_api.language.find_all_languages
            find_by_id:
                sql: public_api.language.find_by_id
                parameters: [id]
                model:
                    object: AdminBundle\Entity\Language

    callable:
        find_all_languages:
            type: object
            name: PublicApi\Language\Repository\BlueDotCallable\FindAllLanguagesCallable