admin_basic_word_game_index:
    path: /games/basic-word-game
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.basic_word_game:indexAction }

#admin_lesson_create:
#    path: /lesson/create
#    methods: [GET]
#    defaults: { _controller: langland.learning_metadata.controller.lesson:createAction }
#
#admin_lesson_update_view:
#    path: /lesson/edit/{lessonId}
#    methods: [GET]
#    defaults: { _controller: langland.learning_metadata.controller.lesson:editViewAction }