admin_api_lesson_new:
    path: /lesson/new
    methods: [POST]
    defaults: { _controller: langland.learning_metadata.controller.lesson_controller:newAction }
    requirements:
        _format: json