admin_lesson_index:
    path: /lessons
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.lesson:indexAction }

admin_lesson_create:
    path: /lesson/create
    methods: [GET]
    defaults: { _controller: langland.learning_metadata.controller.lesson:createAction }