admin_lesson:
  resource: "@AdminBundle/Resources/config/routing/api/course_managment/lesson.yml"
  prefix: /
  host: '%host%'

admin_game:
  resource: "@AdminBundle/Resources/config/routing/api/course_managment/game.yml"
  prefix: /
  host: '%host%'