admin_game_index_get:
    path: /
    defaults: { _controller: AdminBundle:Game:index }
    methods: [GET]

admin_game_remove:
    path: /remove/{gameId}
    defaults: { _controller: AdminBundle:Game:remove }

admin_word_game:
  resource: "@AdminBundle/Resources/config/routing/api/course/game/wordGame.yml"
  prefix: /word-game
  host: '%host%'

admin_question_game:
  resource: "@AdminBundle/Resources/config/routing/api/course/game/questionGame.yml"
  prefix: /question-game
  host: '%host%'