admin_game_index_get:
    path: /
    defaults: { _controller: AdminBundle:Game:index }
    methods: [GET]

admin_word_game_create_get:
    path: /word-game/create
    defaults: { _controller: AdminBundle:Game:create }
    methods: [GET, POST]

admin_find_word_game_words:
    path: /word-game/find-game-words
    defaults: { _controller: AdminBundle:Ajax/Game:findGameWords }
    methods: [GET]

admin_find_lessons_by_course:
    path: /word-game/find-lessons-by-course
    defaults: { _controller: AdminBundle:Ajax/Game:findLessonsByCourse }
    methods: [GET]

admin_find_word_games:
    path: /word-game/find-games
    defaults: { _controller: AdminBundle:Ajax/Game:findGames }
    methods: [GET]

admin_create_word_game:
    path: /word-game/create-game
    defaults: { _controller: AdminBundle:Ajax/Game:createGame }
    methods: [POST]