admin_lesson_index:
    path: /
    defaults: { _controller: AdminBundle:Lesson:index }
    methods: [GET]

admin_lesson_create:
    path: /create
    defaults: { _controller: AdminBundle:Lesson:create }
    methods: [GET, POST]

admin_lesson_edit:
    path: /edit/{lessonId}
    defaults: { _controller: AdminBundle:Lesson:edit }
    methods: [GET, POST]

admin_find_lessons_by_course:
    path: /lessons-by-course
    defaults: { _controller: AdminBundle:Lesson:findLessonsByCourse }
    methods: [GET]