lesson_index:
    path: /
    defaults: { _controller: AdminBundle:Lesson:index }
    methods: [GET]

lesson_create:
    path: /create
    defaults: { _controller: AdminBundle:Lesson:create }
    methods: [GET, POST]

lesson_edit:
    path: /edit/{lessonId}
    defaults: { _controller: AdminBundle:Lesson:edit }
    methods: [GET, POST]