sentence_index:
    path: /
    defaults: { _controller: AdminBundle:Sentence:index }
    methods: [GET]

sentence_create:
    path: /create
    defaults: { _controller: AdminBundle:Sentence:create }
    methods: [GET, POST]

sentence_edit:
    path: /edit/{sentenceId}
    defaults: { _controller: AdminBundle:Sentence:edit }