AdminBundle\Entity\Lesson:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [game, lesson_list, word_games_list]
        name:
            expose: true
            groups: [game, lesson_list, word_games_list]
        description:
            expose: true
            groups: [lesson_list]
        games:
            expose: true
            type: AdminBundle\Entity\Game\WordGame
            groups: [word_games_list]
        isInitialLesson:
            expose: true
            groups: [lesson_list]
            serialized_name: isInitialLesson