AdminBundle\Entity\Language:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [learnable_language]
        name:
            expose: true
            groups: [learnable_language]
        listDescription:
            expose: true
            groups: [learnable_language]
            serialized_name: listDescription
        image:
            expose: true
            type: AdminBundle\Entity\Image
            groups: [learnable_language]