AdminBundle\Entity\Language:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [viewable, signed_courses, course_list]
        name:
            expose: true
            groups: [viewable, signed_courses, course_list]
        listDescription:
            expose: true
            groups: [viewable]
            serialized_name: listDescription