AdminBundle\Entity\Lesson:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [lesson_autocomplete, lesson_list]
        name:
            expose: true
            groups: [lesson_autocomplete, lesson_list]
        description:
            expose: true
            groups: [lesson_list]
        lessonUrl:
            expose: true
            groups: [lesson_list]
            serialized_name: lessonUrl
        lessonTexts:
            expose: true
            groups: [lesson_text]
            type: AdminBundle\Entity\LessonText
            serialized_name: lessonText
        isInitialLesson:
            expose: true
            groups: [lesson_list]
            serialized_name: isInitialLesson