AdminBundle\Entity\Game\WordGame:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [game, word_games_list]
        name:
            expose: true
            groups: [game, word_games_list]
        description:
            expose: true
            groups: [game, word_games_list]
        gameUnits:
            expose: true
            type: AdminBundle\Entity\Game\WordGameUnit
            groups: [game]
            serialized_name: words
        lesson:
            expose: true
            type: AdminBundle\Entity\Lesson
            groups: [game]