AdminBundle\Entity\Image:
    exclusion_policy: ALL
    properties:
        name:
            expose: true
            groups: [learnable_language]
        fullPath:
            expose: true
            groups: [learnable_language]
            serialized_name: fullPath