AdminBundle\Entity\Language:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [viewable, communication_model]

        name:
            expose: true
            groups: [viewable, communication_model]

        listDescription:
            expose: true
            groups: [viewable, communication_model]
            serialized_name: description

        showOnPage:
            expose: true
            groups: [viewable, communication_model]

        images:
            expose: true
            groups: [viewable]

