AdminBundle\Entity\Language:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: int
            groups: [signed_courses]
        name:
            expose: true
            type: string
            groups: [entire_object, signed_courses]