AdminBundle\Entity\Language:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [viewable]
        name:
            expose: true
            groups: [viewable]
        listDescription:
            expose: true
            groups: [viewable]
            serialized_name: desc
        images:
            expose: true
            groups: [viewable]