AdminBundle\Entity\Course:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [course_list, internal_model]

        name:
            expose: true
            groups: [course_list, internal_model]

        whatToLearn:
            expose: true
            groups: [course_list, internal_model]

        courseOrder:
            expose: true
            groups: [internal_model]

        type:
            expose: true
            groups: [internal_model]

        courseUrl:
            expose: true
            groups: [course_list, internal_model]

