AdminBundle\Entity\Language:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [learnable_language]
        name:
            expose: true
            groups: [learnable_language]