AdminBundle\Entity\LanguageInfo:
    exclusion_policy: ALL
    properties:
        name:
            expose: true
            groups: [language_info]
        languageInfoTexts:
            expose: true
            groups: [language_info]
            type: AdminBundle\Entity\LanguageInfoText
            serialized_name: texts