AdminBundle\Entity\Lesson:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [public_api, internal_model]

        name:
            expose: true
            groups: [public_api, internal_model]

        uuid:
            expose: true
            groups: [public_api, internal_model]

        learningOrder:
            expose: true
            groups: [public_api, internal_model]

        description:
            expose: true
            groups: [public_api, internal_model]

        urlifiedName:
            expose: true
            groups: [internal_model]

        jsonLesson:
            expose: true
            type: array
            groups: [public_api, internal_model]

        createdAt:
            expose: true
            type: DateTime<'Y-m-d H:m:s'>
            groups: [internal_model]

        updatedAt:
            expose: true
            type: DateTime<'Y-m-d H:m:s'>
            groups: [internal_model]