AdminBundle\Entity\Language:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [learnable_language, signed_courses, course_list]
        name:
            expose: true
            groups: [learnable_language, signed_courses, course_list]
        listDescription:
            expose: true
            groups: [learnable_language]
            serialized_name: listDescription