AdminBundle\Entity\Lesson:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [public_api]
        uuid:
            expose: true
            groups: [public_api]
        learningOrder:
            serialized_name: learningOrder
            expose: true
            groups: [public_api]
        jsonLesson:
            expose: true
            serialized_name: lesson
            type: array
            groups: [public_api]