AdminBundle\Entity\Course:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [course_list]
        name:
            expose: true
            groups: [course_list]
        whatToLearn:
            expose: true
            groups: [course_list]
            serialized_name: whatToLearn
        initialCourse:
            expose: true
            groups: [course_list]
            serialized_name: initialCourse