make_initial_data_creation:
    path: /make-initial-data-creation
    defaults: { _controller: langland.public_api.controller.lesson:getLessonById }
    methods: [GET]
    requirements:
        _format: json