make_initial_data_creation:
    path: /make-initial-data-creation
    defaults: { _controller: learning_system.business.controller.initial_data_creation:makeInitialDataCreation }
    methods: [POST]
    requirements:
        _format: json