imports:
    - { resource: ../parameters.yml }
    - { resource: security.yml }
    - { resource: "@ArmorBundle/Resources/config/services.xml" }

    - { resource: vendor_config/jms_serializer.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   /var/lib/php/sessions
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

sensio_framework_extra:
    request:
        converters: true
        auto_convert: false

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

monolog:
    channels:
        - generic_exception
    handlers:
        generic_exception:
            type: stream
            path: '%kernel.logs_dir%/exception.log'
            level: alert
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        security:
            level: error
            type: stream
            path: '%kernel.logs_dir%/security.log'
            channels: [security]
        exception:
            level: alert
            type: stream
            path: '%kernel.logs_dir%/exception.log'
        database:
            level: warning
            type: stream
            path: '%kernel.logs_dir%/database.log'
            channels: [doctrine]
        console:
            type: console
            channels: ['!event', '!doctrine']

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
