security:
    encoders:
        ArmorBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        armor_user_provider:
            id: armor.user_provider
        armor_public_api_user_provider:
            id: armor.user_provider.public_api

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: armor_user_provider
            logout_on_user_change: true
            form_login:
                default_target_path: admin_dashboard
                login_path: armor_admin_login
                check_path: armor_admin_login
            anonymous: ~

        langland:
            access_denied_handler: armor.langland.access_denied_handler
            pattern: ^/langland
            logout_on_user_change: true
            provider: armor_user_provider
            user_checker: armor.user.user_checker
            form_login:
                default_target_path: app_language_index
                login_path: armor_user_login
                check_path: armor_user_login
            anonymous: ~

        public_api:
            access_denied_handler: armor.langland.access_denied_handler
            pattern: ^/api
            logout_on_user_change: true
            stateless: true
            provider: armor_public_api_user_provider
            simple_preauth:
                authenticator: armor.authenticator.public_api
            anonymous: ~

        app:
            pattern: ^/
            logout_on_user_change: true
            anonymous: true

    role_hierarchy:
        ROLE_ALLOWED_MODIFY: [ROLE_ALLOWED_VIEW, ROLE_ALLOWED_MODIFY, ROLE_PUBLIC_API_USER]
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_VIEW, ROLE_ALLOWED_MODIFY, ROLE_PUBLIC_API_USER]

    access_control:
        - { path: ^/*$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, role: [ROLE_ADMIN, ROLE_ALLOWED_VIEW, ROLE_ALLOWED_MODIFY] }

        - { path: ^/langland/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/langland/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/langland/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/langland/user/confirm/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/langland/*, role: [ROLE_USER] }

        - { path: ^/api/*, role: [ROLE_PUBLIC_API_USER] }



