security:
    encoders:
        ArmorBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        armor_user_provider:
            id: armor.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: armor_user_provider
            form_login:
                default_target_path: admin_dashboard
                login_path: armor_admin_login
                check_path: armor_admin_login

            anonymous: ~

        langland:
            pattern: ^/langland
            provider: armor_user_provider
            user_checker: armor.user.user_checker
            form_login:
                default_target_path: app_page_main_dashboard
                login_path: armor_user_login
                check_path: armor_user_login

            anonymous: ~

        app:
            pattern: ^/
            anonymous: true

    role_hierarchy:
        ROLE_ALLOWED_MODIFY: [ROLE_ALLOWED_VIEW, ROLE_ALLOWED_MODIFY]
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_VIEW, ROLE_ALLOWED_MODIFY]

    access_control:
        - { path: ^/*$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, role: [ROLE_ADMIN, ROLE_ALLOWED_VIEW, ROLE_ALLOWED_MODIFY] }

        - { path: ^/langland/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/langland/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/langland/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/langland/user/confirm/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/langland/*, role: ROLE_USER }



