# app/config/services.yml
#services:
#    _defaults:
#        autowire: true
#        autoconfigure: true
#        public: false
#
#    Library\:
#        resource: '../../../lib/Library/*'
#
#    AdminBundle\:
#        resource: '../../../src/AdminBundle/*'
#
#    langland.learning_metadata.controller.dashboard_controller:
#        class: Library\LearningMetadata\Business\Controller\DashboardController
#        autowire: true
