configuration:

    simple:
        select:
            check_that_exists:
                sql: "SELECT id AS learning_metadata_exists FROM learning_user_metadata WHERE learning_user_id = :learning_user_id LIMIT 1"
                parameters: [learning_user_id]

    scenario:
        create_learning_metadata:
            atomic: true
            statements:
                create_system_head:
                    sql: "INSERT INTO system_heads"
                create_learning_lesson:
                    sql: "INSERT INTO learning_lessons (system_head_id, lesson_id, has_passed) VALUES (:system_head_id, :lesson_id, 0)"
                    parameters: [lesson_id]
                    foreign_key:
                        statement_name: create_system_head
                        bind_to: system_head_id
                create_learning_metadata:
                    sql: "INSERT INTO learning_metadata (system_head_id, learning_user_id) VALUES(:system_head_id, :learning_user_id)"
                    parameters: [learning_user_id]
                    foreign_key:
                        statement_name: create_system_head
                        bind_to: system_head_id