configuration:

    sql_import: imports/learning_user_metadata.yml

    scenario:
        create_learning_metadata:
            atomic: true
            statements:
                find_lesson:
                    sql: create_learning_metadata.find_lesson
                    parameters: [language_id, course_type, learning_order]
                create_data_collector:
                    sql: create_learning_metadata.create_data_collector
                create_learning_lesson:
                    sql: create_learning_metadata.create_learning_lesson
                    foreign_key:
                        statement_name: create_data_collector
                        bind_to: data_collector_id
                    use:
                        statement_name: find_lesson
                        values: { find_lesson.id : lesson_id }
                create_learning_metadata:
                    sql: create_learning_metadata.create_learning_metadata
                    parameters: [learning_user_id]
                    foreign_key:
                        statement_name: create_data_collector
                        bind_to: data_collector_id